"""Reel — say what it's about, get a finished vertical video.

One prompt and one button. The user never picks a scene type, never sets a
duration, never types a hex code: attach the client's card or logo and the
brand colours are MEASURED off it, the agent writes only the words, and the
renderer draws every frame locally.

Nothing here is generated by a video model, which is exactly why it can be
sold: always 9:16, text always legible, no watermark, no daily credit cap,
and the saved spec re-renders identically forever.
"""
from __future__ import annotations
import json
import os
import subprocess
import sys
import time

from PySide6.QtCore import Qt, QUrl, Signal
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import (
    QDialog, QFrame, QVBoxLayout, QHBoxLayout, QLabel, QPushButton,
    QPlainTextEdit, QMessageBox, QProgressBar, QRadioButton, QButtonGroup,
)

import core_bridge as CB
import i18n
import theme
import wakeword
from dialogs.base import PrismDialog
from widgets import controls as C
from workers import AutomationWorker, RecordWorker, ReelWorker
from widgets.ask_panel import AskPanel


class ReelDialog(PrismDialog):
    # Emitted by the layout editor's local server (from its own thread —
    # Qt queues them onto the UI thread) when the browser presses Save or
    # Save & render.
    edits_saved = Signal(list)
    edits_rendered = Signal(list)

    def __init__(self, cfg: dict, attachments: list, parent=None):
        super().__init__(
            i18n.t("Make a Reel"),
            i18n.t("A finished 9:16 video, drawn frame by frame on this "
                   "machine. No watermark and no daily cap."),
            icon="video", parent=parent, closable=False)
        self.setWindowTitle("Make a Reel")
        self.resize(780, 700)
        self.setMinimumSize(620, 620)
        self.cfg = cfg
        self.reel = CB.get_reel()

        self.images: list[dict] = []
        self.brand: dict = {}
        self.spec: dict | None = None
        self.out_path = ""
        # The findable copy — see config.ARTIFACTS_DIR. `out_path` is where
        # the render actually lands (~/.prism/runs, hidden), which is why
        # Play/Show always prefer this one once it exists.
        self.artifact_path = ""
        self._worker = None
        self._rec = None
        # The browser layout editor: stop() for its server, and whether the
        # last render was Studio's (the editor edits a web page, so the
        # template renderer has nothing for it to open).
        self._edit_stop = None
        self._studio_last = False
        self.edits_saved.connect(self._on_edits_saved)
        self.edits_rendered.connect(self._on_edits_rendered)

        # The base class owns the header and footer; `root` is its body column.
        root = self.body
        # A stacked form, not a grid of cards: the 16px card gutter
        # between every row of a single column is what turns a short
        # form into a tall one with bands of canvas through it.
        root.setSpacing(theme.ROW_GAP)

        title = QLabel("What should the reel be about?")
        title.setObjectName("h4")
        root.addWidget(title)

        self.ask = AskPanel(
            'Just say it — for example:\n'
            '"a reel describing what we sell at Raj Infotech"\n\n'
            "Attach their logo, business card or brochure and the brand "
            "colours are taken straight from it.")
        self.ask.speak_clicked.connect(self._toggle_record)
        self.ask.files_added.connect(self._on_files_added)
        root.addWidget(self.ask)

        # The two renderers, offered rather than assumed.
        #
        # This shelf item has always been called "Reel / Studio" and has only
        # ever run Reel — Studio was reachable solely by configuring it as the
        # video agent and then typing a task on Home, which nobody found. A
        # menu entry naming a thing it cannot do is worse than not offering it.
        self.studio_btn = QRadioButton(
            "Studio — designed for this client. A web page, filmed. "
            "Takes a few minutes.")
        self.reel_btn = QRadioButton(
            "Quick — drawn from templates. Same look every time, ready in "
            "under a minute.")
        self.render_choice = QButtonGroup(self)
        self.render_choice.addButton(self.studio_btn)
        self.render_choice.addButton(self.reel_btn)
        studio_ok, studio_why = CB.studio_available()
        # Studio is the better film, so it is the default wherever it can run.
        (self.studio_btn if studio_ok else self.reel_btn).setChecked(True)
        if not studio_ok:
            self.studio_btn.setEnabled(False)
            self.studio_btn.setToolTip(studio_why)
        # Two loose radio buttons under a prompt read as stray options. They
        # are a real choice between two renderers, so they get a titled well
        # that says so — and each one clears the 28px target.
        choice = QFrame()
        choice.setObjectName("renderChoice")
        choice.setAttribute(Qt.WA_StyledBackground, True)
        choice.setStyleSheet(
            f"#renderChoice {{ background: {theme.WELL};"
            f" border: 1px solid {theme.HAIRLINE};"
            f" border-radius: {theme.R_CONTROL}px; }}")
        choice_col = QVBoxLayout(choice)
        choice_col.setContentsMargins(theme.SPACE_3, theme.SPACE_3,
                                      theme.SPACE_3, theme.SPACE_3)
        choice_col.setSpacing(theme.SPACE_2)
        choice_col.addWidget(C.kicker(i18n.t("How it is made"), muted=True))
        for b in (self.studio_btn, self.reel_btn):
            b.setMinimumHeight(C.MIN_TARGET)
            b.setCursor(Qt.PointingHandCursor)
            choice_col.addWidget(b)
        root.addWidget(choice)

        # A measured result ("your brand colours came off this logo"), not a
        # placeholder, so it stops wearing the dashed empty-state box.
        self.brand_label = QLabel("", self)
        self.brand_label.setWordWrap(True)
        self.brand_label.setVisible(False)
        self.brand_label.setStyleSheet(
            f"color: {theme.OK_INK}; background: {theme.OK_BG};"
            f" border-radius: {theme.R_CONTROL}px;"
            f" padding: {theme.SPACE_2}px {theme.SPACE_3}px;"
            f" font-size: 13px;")
        root.addWidget(self.brand_label)

        self.progress = QProgressBar()
        self.progress.setVisible(False)
        root.addWidget(self.progress)

        self.status = QLabel("")
        self.status.setWordWrap(True)
        root.addWidget(self.status)

        self.script_view = QPlainTextEdit()
        self.script_view.setReadOnly(True)
        self.script_view.setPlaceholderText(
            "The scenes will be listed here once written.")
        self.script_view.setMinimumHeight(150)
        root.addWidget(self.script_view, stretch=1)

        self.edit_btn = self.button(i18n.t("Edit the layout"), "secondary",
                                    icon_name="pencil", small=True,
                                    on_click=self._edit_layout)
        self.edit_btn.setEnabled(False)
        self.edit_btn.setToolTip(i18n.t(
            "Open the reel in your browser: drag anything into place, "
            "resize it, retype it or delete it, then render again. "
            "Studio reels only."))
        self.footer.add_utility(self.edit_btn)
        self.play_btn = self.button(i18n.t("Play"), "secondary",
                                    icon_name="play", small=True,
                                    on_click=self._play)
        self.play_btn.setEnabled(False)
        self.footer.add_utility(self.play_btn)
        self.folder_btn = self.button(i18n.t("Show file"), "secondary",
                                      icon_name="folder", small=True,
                                      on_click=self._reveal)
        self.folder_btn.setEnabled(False)
        self.footer.add_utility(self.folder_btn)
        self.footer.add_secondary(
            self.button(i18n.t("Close"), on_click=self.reject))
        self.run_btn = self.button(i18n.t("Make my reel"), "primary",
                                   icon_name="video", on_click=self._run)
        self.footer.set_primary(self.run_btn)

        if attachments:
            self._absorb([a["path"] for a in attachments])

        # The last Studio reel, back on the bench. Its spec is saved beside
        # the video precisely so it can be reopened — without this, closing
        # the window after a render left "Edit the layout" with nothing to
        # edit and no way back in.
        try:
            last = self._last_studio_reel()
        except Exception:                               # noqa: BLE001
            last = None
        if last:
            self.spec, self.out_path = last
            self._studio_last = True
            self._refresh_edit_btn()
            have_video = os.path.exists(self.out_path)
            self.play_btn.setEnabled(have_video)
            self.folder_btn.setEnabled(have_video)
            self.status.setText(i18n.t(
                "Your last Studio reel is loaded — press Edit the layout to "
                "fix it by hand, or just make a new one."))

    # ── inputs ──────────────────────────────────────────────────────────

    def _on_files_added(self, paths: list):
        self._absorb(paths)

    def _absorb(self, paths: list):
        """Only images matter here — they carry the brand. Anything else is
        ignored rather than refused, so a user who attaches a PDF too isn't
        stopped."""
        for p in paths:
            if not p.lower().endswith((".png", ".jpg", ".jpeg", ".webp", ".bmp")):
                continue
            try:
                att = CB.files.attach(p)
            except Exception:
                continue
            if att["path"] not in [i["path"] for i in self.images]:
                self.images.append(att)
        if not self.images:
            return
        self.brand = self.reel.sample_brand([i["path"] for i in self.images]) or {}
        if self.brand:
            self.brand_label.setText(
                f"Brand colours read from {', '.join(i['name'] for i in self.images)} — "
                f"accent {self.brand.get('accent')}, deep {self.brand.get('deep')}. "
                "Measured from the artwork, not guessed.")
            # Hidden until there is something to say — an empty tinted strip
            # under the prompt is a slot waiting to be filled, which is what
            # the dashed placeholder version of this always looked like.
            self.brand_label.setVisible(True)

    def _toggle_record(self):
        if self._rec:
            self._rec.stop()
            self.ask.set_recording(False)
            return
        if not CB.voice.available():
            QMessageBox.information(
                self, "Speak",
                "Voice needs PyAudio on this machine:\n\n"
                f"    {wakeword.install_hint()}\n\n"
                "Everything else works — just type instead.")
            return
        self.ask.set_recording(True)
        self._rec = RecordWorker(self.cfg)
        self._rec.done.connect(self._on_spoken)
        self._rec.failed.connect(lambda e: self._on_spoken("", ""))
        self._rec.start()

    def _on_spoken(self, text: str, lang: str):
        self._rec = None
        self.ask.set_recording(False)
        if text:
            self.ask.append_text(text)

    # ── the run ─────────────────────────────────────────────────────────

    def _run(self):
        request = self.ask.text()
        if not request:
            QMessageBox.information(self, "Reel", "Tell me what the reel is about.")
            return
        ok, why = CB.reel_available()
        if not ok:
            QMessageBox.warning(self, "Reel", why)
            return

        agents = CB.config.active_agents(self.cfg)
        writer = next((s for s in ("content", "brains", "media") if agents.get(s)), None)
        if not writer:
            QMessageBox.warning(self, "Reel",
                                "No writing agent set up yet — open Agents first.")
            return
        self.request = request

        if self.studio_btn.isChecked():
            self._run_studio(request, agents, writer)
            return

        self._busy(True, f"{agents[writer]} is writing the scenes…")
        prompt = self.reel.build_prompt(request, self.brand, bool(self.images))
        self._worker = AutomationWorker(
            {}, self.cfg, self.images, f"write a reel script — {request}",
            custom_stages=[("script", agents[writer], [prompt])],
            chatgpt_analysis=False)
        self._worker.done.connect(self._on_script)
        self._worker.failed.connect(self._on_failed)
        self._worker.start()

    # ── Studio ──────────────────────────────────────────────────────────
    # Two writing passes, not one. A single reply asked for both the words
    # and the look produces a design that DESCRIBES itself — "clean data
    # card", "logo reveal" — rather than one that exists. The second pass is
    # itself a conversation: the look and a storyboard, then a scene at a
    # time, each laid out at 1080x1920 and corrected before the next.

    def _run_studio(self, request: str, agents: dict, writer: str):
        studio = CB.get_studio()
        assets = CB.get_assets()
        table = {}
        if self.images:
            try:
                table = assets.collect([i["path"] for i in self.images])
            except Exception:
                table = {}
        # The art director is the strongest tool available: this pass is the
        # harder of the two by a distance.
        director = agents.get("brains") or agents.get("content") or agents[writer]
        self._busy(True, f"{agents[writer]} is writing the words…")
        self._worker = AutomationWorker(
            {}, self.cfg, self.images, f"design a reel — {request}",
            custom_stages=[
                ("script", agents[writer],
                 ["Write the script for a short vertical brand reel.\n\n"
                  f"WHAT THE CLIENT ASKED FOR:\n{request}\n\n"
                  + studio.script_instructions()]),
                ("design", director,
                 [studio.design_instructions(self.brand or None, request,
                                             assets.manifest(table))]),
            ],
            chatgpt_analysis=False,
            # Names the stage whose reply is turn one of the design
            # conversation. A routed run infers this from the renderer in its
            # plan; this dialog has no renderer stage, so it says so.
            reel_design_stage="design")
        # Studio's design stage is minutes long — one turn per scene. Without
        # this the window says "writing the words…" for all of it, which is
        # indistinguishable from a hang on a customer's laptop.
        self._worker.stage_event.connect(self._on_studio_event)
        self._worker.done.connect(self._on_design)
        self._worker.failed.connect(self._on_failed)
        self._worker.start()

    def _on_studio_event(self, kind: str, payload: dict):
        if kind == "reel_scene":
            n, total = payload.get("index", 0) + 1, payload.get("total", 0)
            self._busy(True, f"Designing scene {n} of {total} — "
                             "each one is written and laid out on its own.")
            if total:
                self.progress.setRange(0, total)
                self.progress.setValue(n - 1)
        elif kind == "stage_start" and payload.get("stage") == "design":
            self._busy(True, "Choosing the look and storyboarding the "
                             "scenes…")

    def _on_design(self, responses: dict, links: dict):
        studio = CB.get_studio()
        texts = [t for t in (responses.get("design") or []) if t.strip()]
        spec, why = None, None
        for text in reversed(texts):
            try:
                spec = studio.parse_spec(text)
                break
            except Exception as e:                       # noqa: BLE001
                why = why or e
        if spec is None:
            self._busy(False, "")
            kept = self.reel.keep_unparsed(texts or ["(nothing was captured)"],
                                           what="design")
            QMessageBox.warning(
                self, "Reel",
                f"{why or 'The art-direction stage returned nothing.'}"
                + (f"\n\nWhat came back was saved to:\n{kept}" if kept else "")
                + ("\n\nIts tab: " + links["design"] if links.get("design")
                   else ""))
            return

        if self.brand:
            spec["brand"] = self.brand
        if self.images:
            try:
                spec["_assets"] = CB.get_assets().collect(
                    [i["path"] for i in self.images])
            except Exception:
                pass
        self.spec = spec
        self._start_render(spec, studio=True)

    def _start_render(self, spec: dict, studio: bool = False):
        self._studio_last = studio
        lines = [f"{i + 1}. {sc.get('type') or 'scene'}  ·  "
                 f"{sc.get('seconds', 4)}s"
                 f"   {sc.get('heading') or sc.get('name') or ''}"
                 for i, sc in enumerate(spec["scenes"])]
        if spec.get("_dropped"):
            lines.append("")
            lines.append("skipped (this renderer can't draw them): "
                         + ", ".join(spec["_dropped"]))
        self.script_view.setPlainText("\n".join(lines))

        secs = sum(float(sc.get("seconds", 4)) for sc in spec["scenes"])
        os.makedirs(CB.config.RUNS_DIR, exist_ok=True)
        stamp = int(time.time())
        self.out_path = os.path.join(CB.config.RUNS_DIR, f"reel_{stamp}.mp4")
        # Saved beside the video and complete in itself — assets inlined —
        # so it re-renders identically next year without an AI in the loop.
        json.dump(spec, open(
            os.path.join(CB.config.RUNS_DIR, f"reel_{stamp}.json"), "w"),
            indent=2)

        self.progress.setRange(0, 100)
        self._busy(True, f"{'Filming' if studio else 'Drawing'} "
                         f"{len(spec['scenes'])} scenes, {secs:.0f}s, "
                         "1080x1920…")
        self._render_worker = ReelWorker(spec, self.out_path, studio=studio)
        self._render_worker.progress.connect(self._on_frames)
        self._render_worker.done.connect(self._on_rendered)
        self._render_worker.failed.connect(self._on_failed)
        self._render_worker.start()

    def _on_script(self, responses: dict, links: dict):
        texts = [t for t in (responses.get("script") or []) if t.strip()]
        if not texts:
            self._busy(False, "")
            QMessageBox.warning(self, "Reel", "The agent returned nothing.")
            return
        # NEWEST capture that actually parses — not texts[0].
        #
        # texts[0] is whatever is at the TOP of the chat tab, and Prism reuses
        # its browser profile, so on a reused tab that is an older
        # conversation entirely. The page also holds the prompt Prism just
        # typed, which carries an example spec inside it.
        spec, why = self.reel.first_spec(texts)
        if spec is None:
            self._busy(False, "")
            # Keep what came back. Without this the one piece of evidence that
            # could explain the failure is discarded at the moment it becomes
            # interesting — and "No JSON scene spec found in the agent's
            # reply" is unanswerable against a tab that visibly contains JSON.
            kept = self.reel.keep_unparsed(texts)
            QMessageBox.warning(
                self, "Reel",
                f"{why or 'The agent returned nothing to render.'}"
                + (f"\n\nWhat came back was saved to:\n{kept}" if kept else "")
                + ("\n\nIts tab: " + links["script"] if links.get("script")
                   else ""))
            return
        if self.brand:
            spec["brand"] = self.brand
        self.spec = spec
        self._start_render(spec)

    def _on_frames(self, done: int, total: int):
        self.progress.setValue(int(done / max(1, total) * 100))

    def _on_rendered(self, path: str):
        self.play_btn.setEnabled(True)
        self.folder_btn.setEnabled(True)
        self._refresh_edit_btn()
        # A closed Prism used to leave no way back to this file — it only
        # ever lived in ~/.prism/runs (hidden on macOS) or in this dialog's
        # own memory. Copying it out to a named, visible folder is what
        # makes "check it later" possible at all.
        try:
            self.artifact_path = CB.config.save_artifact(
                path, self.request, kind="reel", task=self.request)
        except Exception:                               # noqa: BLE001
            self.artifact_path = ""
        if self.artifact_path:
            self._busy(False, i18n.t(
                "Done — saved to Desktop/Prism Artifacts/{name}").replace(
                "{name}", os.path.basename(self.artifact_path)))
        else:
            self._busy(False, f"Done — {os.path.basename(path)}")
        CB.config.save_run({
            "query": f"reel — {self.request}",
            "reel": {"mp4": path, "brand": self.brand,
                     "artifact": self.artifact_path},
        })

    def closeEvent(self, event):
        """Wind up any worker before this dialog is destroyed.

        A QThread destroyed while still running aborts the whole process, so
        closing this window mid-render took Prism down with it.
        """
        self._stop_editor()
        for worker in (getattr(self, "_worker", None),
                       getattr(self, "_render_worker", None),
                       getattr(self, "_rec", None)):
            if worker is None or not worker.isRunning():
                continue
            if hasattr(worker, "stop"):
                worker.stop()
            if not worker.wait(8000):
                worker.terminate()
                worker.wait(1000)
        super().closeEvent(event)

    def _on_failed(self, error: str):
        self._busy(False, "")
        QMessageBox.warning(self, "Reel", error)

    def _busy(self, busy: bool, message: str):
        self.progress.setVisible(busy)
        if busy and self.progress.maximum() == 0:
            self.progress.setRange(0, 0)
        self.run_btn.setEnabled(not busy)
        if busy:
            self.edit_btn.setEnabled(False)
        else:
            self._refresh_edit_btn()
        self.status.setText(message)

    # ── the browser layout editor ───────────────────────────────────────
    @staticmethod
    def _last_studio_reel():
        """(spec, mp4 path) of the newest saved Studio reel, or None.

        A Studio spec is told from a Quick one by its scenes carrying real
        HTML — the Quick renderer draws from templates and its spec has
        none. Only the newest twenty records are tried; this runs at every
        open of the window."""
        folder = CB.config.RUNS_DIR
        if not os.path.isdir(folder):
            return None
        names = sorted((n for n in os.listdir(folder)
                        if n.startswith("reel_") and n.endswith(".json")),
                       reverse=True)
        for name in names[:20]:
            path = os.path.join(folder, name)
            try:
                with open(path, encoding="utf-8") as f:
                    spec = json.load(f)
            except (OSError, ValueError):
                continue
            if CB.get_reel_edit().is_studio_spec(spec):
                return spec, path[:-5] + ".mp4"
        return None

    def _refresh_edit_btn(self):
        self.edit_btn.setEnabled(bool(self.spec) and self._studio_last)

    def _edit_layout(self):
        """Open the finished reel in the browser with the edit layer on.

        The page is the SAME page the renderer films — fix a text by eye
        there, press Save & render, and the film cannot come out different.
        """
        if not self.spec or not self._studio_last:
            return
        self._stop_editor()
        edit = CB.get_reel_edit()
        try:
            url, self._edit_stop = edit.serve(
                self.spec,
                on_save=self.edits_saved.emit,
                on_render=self.edits_rendered.emit)
        except Exception as e:                          # noqa: BLE001
            QMessageBox.warning(self, "Reel", i18n.t(
                "Could not open the editor: {error}").format(error=e))
            return
        QDesktopServices.openUrl(QUrl(url))
        self.status.setText(i18n.t(
            "The reel is open in your browser. Click a thing, drag it into "
            "place, then press Save & render there — the new video renders "
            "here."))

    def _keep_edits(self, edits: list):
        """The edits into the spec, and the spec back onto disk, so the
        saved copy re-renders with the fixes even next year."""
        self.spec["edits"] = edits
        if self.out_path.endswith(".mp4"):
            try:
                json.dump(self.spec, open(self.out_path[:-4] + ".json", "w"),
                          indent=2)
            except OSError:
                pass    # the render still carries the edits in memory

    def _on_edits_saved(self, edits: list):
        self._keep_edits(edits)
        self.status.setText(i18n.t(
            "Layout saved — {n} change(s). Press Save & render in the "
            "browser when you are happy with it.").format(n=len(edits)))

    def _on_edits_rendered(self, edits: list):
        self._keep_edits(edits)
        self._stop_editor()
        self._start_render(self.spec, studio=True)

    def _stop_editor(self):
        if self._edit_stop is not None:
            try:
                self._edit_stop()
            except Exception:                           # noqa: BLE001
                pass
            self._edit_stop = None

    # ── output ──────────────────────────────────────────────────────────
    # The render itself lands in ~/.prism/runs, which is hidden on macOS —
    # so these open the Desktop/Prism Artifacts copy instead wherever one
    # exists (see _on_rendered), and fall back to the hidden path only if
    # that copy could not be made.

    def _play(self):
        path = self.artifact_path or self.out_path
        if not path:
            return
        if sys.platform == "darwin":
            subprocess.Popen(["open", path])
        elif os.name == "nt":
            os.startfile(path)  # noqa: F821
        else:
            subprocess.Popen(["xdg-open", path])

    def _reveal(self):
        # The artifact copy first: it sits in Desktop/Prism Artifacts, a
        # folder the owner can find again without Prism open, unlike
        # ~/.prism/runs.
        path = self.artifact_path or self.out_path
        if not path:
            return
        if sys.platform == "darwin":
            subprocess.Popen(["open", "-R", path])
        elif os.name == "nt":
            subprocess.Popen(["explorer", "/select,", path])
        else:
            subprocess.Popen(["xdg-open", os.path.dirname(path)])
