"""Reel — say what it's about, get a finished vertical video.

One prompt and one button. The user never picks a scene type, never sets a
duration, never types a hex code: attach the client's card or logo and the
brand colours are MEASURED off it, the agent writes only the words, and the
renderer draws every frame locally.

Nothing here is generated by a video model, which is exactly why it can be
sold: always 9:16, text always legible, no watermark, no daily credit cap,
and the saved spec re-renders identically forever.
"""
from __future__ import annotations
import json
import os
import subprocess
import sys
import time

from PySide6.QtWidgets import (
    QDialog, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QPlainTextEdit,
    QMessageBox, QProgressBar,
)

import core_bridge as CB
import wakeword
from workers import AutomationWorker, RecordWorker, ReelWorker
from widgets.ask_panel import AskPanel


class ReelDialog(QDialog):
    def __init__(self, cfg: dict, attachments: list, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Make a Reel")
        self.resize(720, 640)
        self.cfg = cfg
        self.reel = CB.get_reel()

        self.images: list[dict] = []
        self.brand: dict = {}
        self.spec: dict | None = None
        self.out_path = ""
        self._worker = None
        self._rec = None

        root = QVBoxLayout(self)

        title = QLabel("What should the reel be about?")
        title.setObjectName("h2")
        root.addWidget(title)

        self.ask = AskPanel(
            'Just say it — for example:\n'
            '"a reel describing what we sell at Raj Infotech"\n\n'
            "Attach their logo, business card or brochure and the brand "
            "colours are taken straight from it.")
        self.ask.speak_clicked.connect(self._toggle_record)
        self.ask.files_added.connect(self._on_files_added)
        root.addWidget(self.ask)

        self.brand_label = QLabel("")
        self.brand_label.setObjectName("emptyState")
        self.brand_label.setWordWrap(True)
        root.addWidget(self.brand_label)

        self.progress = QProgressBar()
        self.progress.setVisible(False)
        root.addWidget(self.progress)

        self.status = QLabel("")
        self.status.setWordWrap(True)
        root.addWidget(self.status)

        self.script_view = QPlainTextEdit()
        self.script_view.setReadOnly(True)
        self.script_view.setPlaceholderText(
            "The scenes will be listed here once written.")
        self.script_view.setMinimumHeight(150)
        root.addWidget(self.script_view, stretch=1)

        btns = QHBoxLayout()
        self.play_btn = QPushButton("Play")
        self.play_btn.setEnabled(False)
        self.play_btn.clicked.connect(self._play)
        btns.addWidget(self.play_btn)
        self.folder_btn = QPushButton("Show file")
        self.folder_btn.setEnabled(False)
        self.folder_btn.clicked.connect(self._reveal)
        btns.addWidget(self.folder_btn)
        btns.addStretch(1)
        close = QPushButton("Close")
        close.clicked.connect(self.reject)
        btns.addWidget(close)
        self.run_btn = QPushButton("Make my reel")
        self.run_btn.setObjectName("primary")
        self.run_btn.setDefault(True)
        self.run_btn.clicked.connect(self._run)
        btns.addWidget(self.run_btn)
        root.addLayout(btns)

        if attachments:
            self._absorb([a["path"] for a in attachments])

    # ── inputs ──────────────────────────────────────────────────────────

    def _on_files_added(self, paths: list):
        self._absorb(paths)

    def _absorb(self, paths: list):
        """Only images matter here — they carry the brand. Anything else is
        ignored rather than refused, so a user who attaches a PDF too isn't
        stopped."""
        for p in paths:
            if not p.lower().endswith((".png", ".jpg", ".jpeg", ".webp", ".bmp")):
                continue
            try:
                att = CB.files.attach(p)
            except Exception:
                continue
            if att["path"] not in [i["path"] for i in self.images]:
                self.images.append(att)
        if not self.images:
            return
        self.brand = self.reel.sample_brand([i["path"] for i in self.images]) or {}
        if self.brand:
            self.brand_label.setText(
                f"Brand colours read from {', '.join(i['name'] for i in self.images)} — "
                f"accent {self.brand.get('accent')}, deep {self.brand.get('deep')}. "
                "Measured from the artwork, not guessed.")

    def _toggle_record(self):
        if self._rec:
            self._rec.stop()
            self.ask.set_recording(False)
            return
        if not CB.voice.available():
            QMessageBox.information(
                self, "Speak",
                "Voice needs PyAudio on this machine:\n\n"
                f"    {wakeword.install_hint()}\n\n"
                "Everything else works — just type instead.")
            return
        self.ask.set_recording(True)
        self._rec = RecordWorker(self.cfg)
        self._rec.done.connect(self._on_spoken)
        self._rec.failed.connect(lambda e: self._on_spoken("", ""))
        self._rec.start()

    def _on_spoken(self, text: str, lang: str):
        self._rec = None
        self.ask.set_recording(False)
        if text:
            self.ask.append_text(text)

    # ── the run ─────────────────────────────────────────────────────────

    def _run(self):
        request = self.ask.text()
        if not request:
            QMessageBox.information(self, "Reel", "Tell me what the reel is about.")
            return
        ok, why = CB.reel_available()
        if not ok:
            QMessageBox.warning(self, "Reel", why)
            return

        agents = CB.config.active_agents(self.cfg)
        writer = next((s for s in ("content", "brains", "media") if agents.get(s)), None)
        if not writer:
            QMessageBox.warning(self, "Reel",
                                "No writing agent set up yet — open Agents first.")
            return
        self.request = request

        self._busy(True, f"{agents[writer]} is writing the scenes…")
        prompt = self.reel.build_prompt(request, self.brand, bool(self.images))
        self._worker = AutomationWorker(
            {}, self.cfg, self.images, f"write a reel script — {request}",
            custom_stages=[("script", agents[writer], [prompt])],
            chatgpt_analysis=False)
        self._worker.done.connect(self._on_script)
        self._worker.failed.connect(self._on_failed)
        self._worker.start()

    def _on_script(self, responses: dict, links: dict):
        texts = [t for t in (responses.get("script") or []) if t.strip()]
        if not texts:
            self._busy(False, "")
            QMessageBox.warning(self, "Reel", "The agent returned nothing.")
            return
        # NEWEST capture that actually parses — not texts[0].
        #
        # texts[0] is whatever is at the TOP of the chat tab, and Prism reuses
        # its browser profile, so on a reused tab that is an older
        # conversation entirely. The page also holds the prompt Prism just
        # typed, which carries an example spec inside it.
        spec, why = self.reel.first_spec(texts)
        if spec is None:
            self._busy(False, "")
            # Keep what came back. Without this the one piece of evidence that
            # could explain the failure is discarded at the moment it becomes
            # interesting — and "No JSON scene spec found in the agent's
            # reply" is unanswerable against a tab that visibly contains JSON.
            kept = self.reel.keep_unparsed(texts)
            QMessageBox.warning(
                self, "Reel",
                f"{why or 'The agent returned nothing to render.'}"
                + (f"\n\nWhat came back was saved to:\n{kept}" if kept else "")
                + ("\n\nIts tab: " + links["script"] if links.get("script")
                   else ""))
            return
        if self.brand:
            spec["brand"] = self.brand
        self.spec = spec

        lines = [f"{i + 1}. {sc.get('type')}  ·  {sc.get('seconds', 4)}s"
                 f"   {sc.get('heading') or sc.get('name') or ''}"
                 for i, sc in enumerate(spec["scenes"])]
        if spec.get("_dropped"):
            lines.append("")
            lines.append("skipped (this renderer can't draw them): "
                         + ", ".join(spec["_dropped"]))
        self.script_view.setPlainText("\n".join(lines))

        secs = sum(float(sc.get("seconds", 4)) for sc in spec["scenes"])
        os.makedirs(CB.config.RUNS_DIR, exist_ok=True)
        stamp = int(time.time())
        self.out_path = os.path.join(CB.config.RUNS_DIR, f"reel_{stamp}.mp4")
        json.dump(spec, open(
            os.path.join(CB.config.RUNS_DIR, f"reel_{stamp}.json"), "w"), indent=2)

        self.progress.setRange(0, 100)
        self._busy(True, f"Drawing {len(spec['scenes'])} scenes, {secs:.0f}s, "
                         "1080x1920…")
        self._render_worker = ReelWorker(spec, self.out_path)
        self._render_worker.progress.connect(self._on_frames)
        self._render_worker.done.connect(self._on_rendered)
        self._render_worker.failed.connect(self._on_failed)
        self._render_worker.start()

    def _on_frames(self, done: int, total: int):
        self.progress.setValue(int(done / max(1, total) * 100))

    def _on_rendered(self, path: str):
        self._busy(False, f"Done — {os.path.basename(path)}")
        self.play_btn.setEnabled(True)
        self.folder_btn.setEnabled(True)
        CB.config.save_run({
            "query": f"reel — {self.request}",
            "reel": {"mp4": path, "brand": self.brand},
        })

    def closeEvent(self, event):
        """Wind up any worker before this dialog is destroyed.

        A QThread destroyed while still running aborts the whole process, so
        closing this window mid-render took Prism down with it.
        """
        for worker in (getattr(self, "_worker", None),
                       getattr(self, "_render_worker", None),
                       getattr(self, "_rec", None)):
            if worker is None or not worker.isRunning():
                continue
            if hasattr(worker, "stop"):
                worker.stop()
            if not worker.wait(8000):
                worker.terminate()
                worker.wait(1000)
        super().closeEvent(event)

    def _on_failed(self, error: str):
        self._busy(False, "")
        QMessageBox.warning(self, "Reel", error)

    def _busy(self, busy: bool, message: str):
        self.progress.setVisible(busy)
        if busy and self.progress.maximum() == 0:
            self.progress.setRange(0, 0)
        self.run_btn.setEnabled(not busy)
        self.status.setText(message)

    # ── output ──────────────────────────────────────────────────────────
    # The file lands in ~/.prism/runs, which is hidden on macOS — so the
    # dialog opens it directly rather than telling the user a path they
    # cannot find in Finder.

    def _play(self):
        if not self.out_path:
            return
        if sys.platform == "darwin":
            subprocess.Popen(["open", self.out_path])
        elif os.name == "nt":
            os.startfile(self.out_path)  # noqa: F821
        else:
            subprocess.Popen(["xdg-open", self.out_path])

    def _reveal(self):
        if not self.out_path:
            return
        if sys.platform == "darwin":
            subprocess.Popen(["open", "-R", self.out_path])
        elif os.name == "nt":
            subprocess.Popen(["explorer", "/select,", self.out_path])
        else:
            subprocess.Popen(["xdg-open", os.path.dirname(self.out_path)])
