"""Rebuilds docs/handover/India_Plastic_Mould_Makers_Estimation_Leads.xlsx —
the lead list researched on 4 Sep 2026 (public sources only, no Apollo)."""
import os
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

NP = "Not published"
L = "https://www.linkedin.com/in/"
IL = "https://in.linkedin.com/in/"

ROWS = [
 ("Godrej Tooling (Godrej & Boyce Mfg. Co. Ltd.)", "Vikhroli, Mumbai, Maharashtra", "Ramachandran T", "Sr. Manager – Design & Estimation, Godrej Tooling Division", NP + " (Plant 7, Pirojshanagar)", "Website contact form", "https://www.godrejenterprises.com/advanced-engineering/tooling", "India's oldest commercial tool room (1935); IMS-certified division of Godrej & Boyce building die-casting dies, plastic injection moulds, press tools and industrial machines, with engineering and tool-maintenance services.", L + "ramachandran-t-6443a427", "Automotive, appliances, aerospace", "Yes", "Commercial tool room", "2026-08-01", "Exact 'Estimation' title."),
 ("Sridevi Tool Engineers Pvt Ltd", "Vasai East, Palghar, Maharashtra", "Britisha Tuscano", "Sr. Executive – Costing", "+91 99879 24808 (company)", "info@sridevitools.com", "https://www.sridevitools.com", "Est. 1972; one of India's largest commercial tool rooms (50,000 sq ft) designing and manufacturing plastic injection moulds for automotive, white goods and luggage; ~150 staff.", L + "britisha-tuscano-31b991225", "Automotive, white goods", "Yes", "Commercial tool room", "2026-08-03", "Costing role since Dec 2024."),
 ("Sanko Svance JRG Tooling India Pvt Ltd", "Bawal, Rewari, Haryana", "Shakeb Khan", "Assistant Manager – Tooling estimation & costing (techno-commercial)", NP, NP, "https://www.sojitz.com/en/corporate/group/company_14014.html", "JV of Sanko Gosei, Sojitz and S-Vance (Japan) with JRG (India), est. 2012; builds large automotive plastic injection moulds and does mould maintenance/ECN work at HSIIDC Bawal.", L + "shakeb-khan-%E3%82%B7%E3%82%A7%E3%82%B1%E3%83%96%E3%83%BB%E3%82%AB%E3%83%BC%E3%83%B3-a712ab143", "Automotive", "Yes", "Commercial tool room", "2026-08-02", "Plot 16, Sector 5, HSIIDC Bawal 123501 (IndiaMART/Justdial). No own website found."),
 ("Radiant Design (RDES Engineering Pvt Ltd)", "Ambattur, Chennai, Tamil Nadu", "Shibu M S", "Manager – Costing", "+91 98416 41651", "info@radiantdesign.in", "https://www.radiantdesign.in", "ISO 9001:2015 manufacturer (est. 2014) of injection mould tools and plastic parts; design-to-manufacturing for enclosures, overmoulding and insert moulding.", L + "msshibumohan", "Automotive, EV, consumer/toys", "Yes", "Commercial tool room", "2026-08-07", ""),
 ("MacPro Technologies Pvt Ltd", "Virgonagar, Bengaluru, Karnataka", "Akash K V", "Process Planning & Estimation Engineer", "+91 80888 92926", "info@macpro-technologies.com", "https://macpro-technologies.com", "Terminal Technologies subsidiary (2010); ISO/IATF-certified toolmaker of high-precision plastic injection moulds (incl. 2K), stamping dies and components.", L + "akash-k-v-aab201226", "Automotive, electrical/electronics", "Yes", "Commercial tool room", "2026-08-03", "Exact 'Estimation' title."),
 ("Jyoti Plastic Works Pvt Ltd (Jyoti World)", "Malad West, Mumbai, Maharashtra", "Prashant Mistry", "Project Manager – Engineering (mould & product cost estimation)", "+91 22 2882 4448", "marketing@jyotiworld.com", "https://jyotiworld.com", "Est. 1959; custom injection moulder with in-house tool room, tooling, compounding and extrusion for engineering and metal-replacement components; exports.", L + "prashant-mistry-0a0252152", "Automotive, fluid engineering, industrial", "Yes", "Moulder with in-house tool room", "2026-08-03", "Second contact: Pratik Trivedi, Cost Estimator (" + L + "pratik-trivedi-9680b8310)."),
 ("Micro Plastics Pvt Ltd", "Bengaluru / Harohalli, Karnataka", "Rayan Chandsha", "Senior Costing Engineer (product & tooling cost)", "+91 80 2219 1600", "info@microplasticsindia.com", "https://microplasticsindia.com", "Tooling and precision injection-moulded components plus contract toy manufacturing; ~245 staff; exports to US, UK and EU brands.", L + "muthahir-rayan", "Toys, automotive, power tools, appliances", "Yes", "Moulder with in-house tool room", "2026-08-07", "Second contact: Adithya Devadiga, Costing Engineer (" + L + "adithyadev)."),
 ("OMG Auto Mould Pvt Ltd (Om Galaxy group)", "Vasai / Palghar, Maharashtra", "Sarath Sankar", "Assistant Manager – Techno-Commercial (mould costing)", "+91 98924 23179", "info@omgautomould.com", "https://www.omgautomould.com", "Tool room designing and manufacturing small-to-large injection moulds for automotive and white-goods OEMs and Tier-1s.", L + "sarath-sankar-bb128a178", "Automotive, white goods", "Yes", "Commercial tool room", "2026-08-19", ""),
 ("Omni Matrix Pvt Ltd", "Doddaballapura, Bengaluru, Karnataka", "Amit Katte", "Marketing Engineer – RFQ costing & quotation (plastic injection moulds)", "+91 99725 77333", "enquiries@omnimatrixindia.com", "https://omnimatrixindia.com", "IATF 16949 family firm (25 years): mould and die DFM-design-manufacture-proving, engineering-plastic injection moulding, precision components; exports to EU, US, Asia.", IL + "amit-katte-2915b5204", "Automotive, medical, electrical", "Yes", "Commercial tool room", "2026-08-27", "In role since Jan 2026; ex-Mastercraft Engineers RFQ desk."),
 ("VEM Tooling India (VEM Group)", "Loni Kalbhor, Pune, Maharashtra", "Ganesh Gadade", "Senior Engineer – Costing / NPD", NP, "Website contact form", "https://www.vem-tooling.com", "US-owned group's 100%-owned Pune plant builds SPI Class 101 multi-cavity injection moulds in-house and moulds parts for medical, automotive and electronics.", L + "ganesh-gadade-02a15718a", "Medical, automotive, electronics", "Yes", "Commercial tool room (Indian plant of US group)", "2026-02-27", "Foreign parent; manufacturing is in Pune."),
 ("Precision Moulds And Dies Pvt Ltd (PMD)", "Sahibabad, Ghaziabad, Uttar Pradesh", "Mukesh Kumar", "General Manager – Tool Room (techno-commercial)", "+91 120 437 2604", "pmd@pmd-india.com", "https://pmd-india.com", "One-stop mould maker: fully hardened precision injection moulds (FMCG, PET preform) plus plastic parts production; product and engineering design in-house.", L + "mukesh-kumar-4609b475", "FMCG packaging, consumer", "Yes", "Commercial tool room", "2026-08-17", "No separate estimation title public; GM owns techno-commercial."),
 ("Indo-German Tool Room (IGTR) Aurangabad", "Chikalthana, Aurangabad, Maharashtra", "Prashant Patil", "Marketing Engineer (quotations & proposals)", "+91 240 261 0100", "marketing@igtr-aur.org", "https://igtr-aur.org", "Government of India (MSME) tool room, est. 1990; ISO-certified production centre making moulds, dies and press tools for industry alongside training.", L + "prashant-patil-8a9b1821a", "Automotive, general engineering", "Yes", "Government commercial tool room", "2026-07-30", ""),
 ("MSME Tool Room Indore (Indo-German Tool Room)", "Indore, Madhya Pradesh", "Chandra Sen Sharma", "Manager – Consultancy & Marketing (RFQs)", "+91 731 421 0700", "gm@igtr-indore.com", "https://www.igtr-indore.com", "Central-government tool room (1995) serving central India: injection moulds (incl. FFS/BFS pharma moulds), press tools and precision machining.", L + "chandra-sen-sharma-11044844", "Pharma packaging, engineering", "Yes", "Government commercial tool room", "2026-08-22", ""),
 ("Motherson Automotive Technologies & Engineering (MATE) – Tooling", "Sanand, Ahmedabad, Gujarat (also Chennai, Puducherry)", "Vinay Mishra", "AGM – Program Management (mould quotations)", NP + " (group address directory)", "Website contact form", "https://www.motherson.com/company/business-divisions/modules-and-polymer-products", "Motherson's commercial tool rooms take injection moulds from tool design to manufacture for automotive, white goods, medical and electrical customers.", IL + "vinay-mishra-144b9989", "Automotive", "Yes", "Group commercial tool room", "2026-08-07", ""),
 ("SFO Technologies (NeST Group) – Bengaluru tool room", "Bengaluru, Karnataka (HQ Kochi, Kerala)", "Mahammad Afroz Naregal", "Engineer – Costing & Sourcing, Business Development Group", "+91 484 661 4300", "contact@nestgroup.net", "https://sfotechnologies.net", "ODM-plus manufacturer whose Bengaluru tool room builds injection moulds and stamping dies for connectors and electronics; ~2,000 staff.", L + "mahammad-afroz-naregal-b2b042207", "Electronics, connectors, aerospace", "Yes", "Captive + commercial tool room", "2026-08-19", "Second contact: Swasthik P D, Estimation & Costing Engineer, since Jun 2026 (" + L + "swasthik-pd)."),
 ("Vasantha Tool Crafts Pvt Ltd (Vasantha Group)", "Jeedimetla, Hyderabad, Telangana", "Chandramohan Golla", "Asst. Manager – Project Engineering & Sales (mould price estimation)", NP, NP, "https://vasantha.com", "Est. 1989; designs and builds precision injection moulds (two-shot, cube, in-mould closing) for packaging, medical and consumer goods; global customers, ~160 staff.", IL + "chandramohan-golla-01a86731", "Packaging, medical, consumer goods", "Yes", "Commercial tool room", "2026-08-03", "Quotes moulds, spares and parts per profile."),
 ("Craftsman Automation Ltd – Tool Room division", "Coimbatore, Tamil Nadu", "Ss Saravanan", "Asst. Manager – Tool Room (cost estimation & quotes)", NP, "Website contact form", "https://www.craftsmanautomation.com", "Listed engineering group; its Tool Room and Mould Base divisions quote and build plastic injection moulds, press tools and die-casting dies.", L + "ss-saravanan-412ba237", "Automotive, industrial", "Yes", "Commercial tool room within group", "2026-08-02", ""),
 ("Skytech Dies and Moulds Pvt Ltd (Skytech Engineering)", "Dharwad, Karnataka", "Nishant Kurandwad", "NPD & Techno-Commercial Team Leader", "+91 836 297 7244", "info@skytechdwd.com", "https://skytechdwd.com", "North-Karnataka tool room and moulding shop building moulds and tools for automotive, electricals, appliances, telecom and caps & closures.", L + "nishant-kurandwad-0563596a", "Automotive, appliances, caps & closures", "Yes", "Commercial tool room", "2026-08-03", ""),
 ("Kraftsman Tooling Pvt Ltd", "Pune, Maharashtra", "Narayanan P S", "Sales & Marketing Manager", "+91 90498 00172", "jerald.davis@kraftsmantooling.com", "https://kraftsmantooling.com", "Precision mould maker (2004) designing and manufacturing injection moulds (1K/2K, prototype) and mould parts for Tier-1s and tool rooms, incl. European clients.", L + "narayanan-p-s-490176201", "Automotive, packaging, consumer", "Yes", "Commercial tool room", "2026-08-02", "Quotes go through sales; no estimation title public."),
 ("Mutual Engineering Pvt Ltd (MEPL)", "Vasai East, Palghar, Maharashtra", "Puneet Narang", "Business Development Manager – Tooling (RFQ & cost settlement)", "+91 91520 09012", "bd@mutualengineering.in", "https://www.mutualengineering.in", "Mould making since 1979; first Indian tool shop to build large SUV bumper moulds; series-production injection moulds, design engineering, project management.", IL + "puneet-narang-56396355", "Automotive, appliances", "Yes", "Commercial tool room", "2026-07-22", ""),
 ("CNH Moulds Pvt Ltd (Besmak group)", "Oragadam, Sriperumbudur, Tamil Nadu", "Saravanan M", "Sr. Executive – Sales & Business Development (tool costing)", "+91 44 6712 3355", "sales@cnhmoulds.com", "https://www.cnhmoulds.com", "Besmak subsidiary (2012) making high-precision multi-cavity injection moulds with 3D product and mould design in-house; ~35 staff.", L + "saravanan-m-5899ba245", "Automotive connectors, electrical", "Yes", "Commercial tool room", "2026-08-29", ""),
 ("CAM Tools Industries Pvt Ltd", "Mumbai, Maharashtra", "Samir Panchal", "Director – Business Development & CTO", "+91 22 2852 1358", "info@ctipl.in", "https://ctipl.in", "ISO 9001 / IATF-certified precision mould maker (1998) and injection moulder for automotive, engineering, medical and toy parts.", IL + "samir-panchal-cam-tools", "Automotive, medical, toys", "Yes", "Commercial tool room", "2026-07-31", "Director level; quotations run through BD."),
 ("Devu Tools Pvt Ltd", "Mumbai (Kandivali / Vasai), Maharashtra", "Mithun Sheregar", "Business Development Manager", "+91 22 6128 2626", "marketing@devutools.com", "https://devutools.com", "One of India's largest mould makers (1993; 100–150 staff) building moulds for automotive, pipe fittings, caps & closures and consumer packaging.", L + "mithun-sheregar-a6337b295", "Automotive, pipe fittings, packaging", "Yes", "Commercial tool room", "2026-01-06", "Closest public contact; no estimation title found."),
 ("Radiant Innovative Manufacturing Ltd (Radiant Polymers)", "Greater Noida, Uttar Pradesh (HQ New Delhi)", "Faiyaz Malik", "Engineering Manager – Plastic injection mould manufacturing (mould costing)", "+91 11 4595 2200", "info@radiantindustries.in", "https://www.radiantindustries.in", "Listed plastics manufacturer (1989) with in-house tool design and development, injection moulding and assemblies for automotive and lighting OEMs.", IL + "faiyaz-malik", "Automotive, lighting, industrial", "Yes", "Moulder with in-house tool room", "2026-08-02", ""),
 ("Lumax Industries Ltd – NPD Mould & Die Group", "Pune, Maharashtra", "Vinod Agrahari", "Techno-Commercial – NPD Mould & Die Group (tool costing, RFQ)", "+91 11 4985 7832 (registered office)", "Website contact form", "https://www.lumaxworld.in/lumaxindustries/index.html", "Automotive-lighting major whose in-house mould and die group develops injection moulds for its lamps and appliance work.", L + "vinod-agrahari-a6077220", "Automotive lighting", "Yes", "Captive tool room", "2026-08-28", ""),
 ("Polyplastics Industries India Pvt Ltd", "Pune, Maharashtra (HQ Yamunanagar, Haryana)", "Nachiketa Kumar", "Manager – NPD & Tooling (tooling RFQ & costing)", NP, "enquiry.marketing@polyplasticindia.com", "https://polyplasticsindia.com", "Auto-accessory moulder (1970, ~470 staff) that has built ~150 injection moulds in-house and developed 700+ with Indian and overseas toolmakers.", L + "nachiketa-kumar-2429b2181", "Automotive accessories", "Yes", "Captive tool room", "2026-08-29", ""),
 ("Mold-Tek Packaging Ltd", "Hyderabad, Telangana", "Venkat Tupakula (ACMA)", "Deputy Manager – Costing & Commercial (pricing & quotation)", "+91 40 4030 0300", "info@moldtekpackaging.com", "https://moldtekpackaging.com", "Listed rigid-packaging leader (38 years, 10 plants); Asia's only fully backward-integrated operation with its own tool room and 50-person design studio.", L + "acma-venkat-tupakula-809720175", "Packaging (paints, food, lubricants)", "Yes", "Captive tool room", "2026-08-18", ""),
 ("Arce Polymers Pvt Ltd / ACME Toolings", "Jeedimetla, Hyderabad, Telangana", "Nikhil Magathoti", "Business Development Engineer – Costing & Estimation", NP, NP, "https://acmetoolings.com", "Moulder with 100+ machines and its own precision tooling unit ACME Toolings (3,000+ moulds built) for appliances, automotive and thermoset parts.", L + "nikhil-magathoti-644ab0239", "Appliances, automotive", "Yes", "Group with commercial tool room", "2026-07-29", "Junior (under 2 years)."),
 ("JSG Innotech Pvt Ltd", "Kundli, Sonipat, Haryana", "Anurag Chaturvedi", "AGM – Business Development & NPD (mould cost calculation)", "+91 85888 55522", "info@jsg.asia", "https://jsginnotech.com", "Car-accessory maker (~240 staff) with in-house tool rooms, injection moulding and chrome-on-plastic lines.", IL + "anurag-chaturvedi-173a1b63", "Automotive accessories", "Yes", "Captive tool room", "2026-07-15", ""),
 ("Sri Lakshmi Engineering", "Chennai, Tamil Nadu", "Bharath S", "Engineer – Cost estimation for plastic injection moulds", NP, NP, "Not verified", "Chennai mould maker quoting injection moulds, parts and fixtures to automotive OEMs and Tier-1s per employee profile; company website could not be verified.", IL + "bharath-s-a6a8231b8", "Automotive", "Yes", "Unverified", "2026-08-19", "LOW CONFIDENCE: company identity not confirmed beyond the profile."),
]

HEAD = ["Company Name", "City/State", "Estimation Manager Name", "Title", "Direct Phone", "Email", "Website",
        "Brief Company Profile (≤50 words)", "Source URL", "Primary Industry Focus",
        "LinkedIn Availability (Yes/No)", "Mould business type", "Profile last seen", "Notes / second contact"]

wb = Workbook(); ws = wb.active; ws.title = "Leads"; ws.append(HEAD)
for r in ROWS:
    assert len(r) == len(HEAD), r[0]
    ws.append(list(r))
bold = Font(bold=True, color="FFFFFF"); fill = PatternFill("solid", fgColor="1F4E78")
for c in ws[1]:
    c.font = bold; c.fill = fill; c.alignment = Alignment(wrap_text=True, vertical="top")
for i, w in enumerate([34, 26, 22, 38, 24, 30, 34, 60, 46, 26, 12, 24, 13, 40], 1):
    ws.column_dimensions[get_column_letter(i)].width = w
for row in ws.iter_rows(min_row=2):
    for c in row:
        c.alignment = Alignment(wrap_text=True, vertical="top")
ws.freeze_panes = "A2"; ws.auto_filter.ref = ws.dimensions

n = len(ROWS)
phones = sum(1 for r in ROWS if r[4].startswith("+"))
emails = sum(1 for r in ROWS if "@" in r[5])
exact = sum(1 for r in ROWS if "stimat" in r[3].split("(")[0])
commercial = sum(1 for r in ROWS if "ommercial" in r[11] and "aptive" not in r[11])
recent = sum(1 for r in ROWS if r[12] >= "2026-07-06")
M = [
 ("Scope", f"{n} Indian companies that manufacture plastic injection moulds, each with one named person who owns mould estimation, costing or quotation. Compiled 4 Sep 2026 from free public sources only."),
 ("What 'estimation manager' means here", f"Only {exact} companies publish someone with 'Estimation' literally in the title. Indian tool rooms usually put mould pricing under Costing, Techno-Commercial, NPD/Tooling or Business Development. Each row names the person whose public profile describes mould cost estimation, RFQ costing or quotation work. Column 'Notes' flags where the title is a stretch."),
 ("Step 1 – Find the companies", "Seeded from TAGMA-style lists of Indian tool rooms, 'top injection mould maker' round-ups, and company pages indexed by the Exa search engine (category:company) for mould manufacturing in Mumbai/Vasai, Pune, Bengaluru, Chennai, Hyderabad, NCR, Coimbatore, Aurangabad, Indore and Dharwad. Websites were opened to confirm the company designs and builds moulds in India."),
 ("Step 2 – Find the person", "Public LinkedIn profiles via the Exa index (category:people) with ~40 queries combining estimation/costing/quotation/techno-commercial with mould, tool room, injection mould and the company names. Each shortlisted profile was opened and its current role, employer, location and responsibilities read in full."),
 ("Step 3 – Company contact details", "Phone, email and website taken from the company's own site or its indexed company record. Where a company publishes only a form, the Email column says so. No personal mobile numbers or personal emails are included because none are public; 'Direct Phone' therefore holds the company line."),
 ("Verification performed", f"(a) Employer, title and India location confirmed on the profile page; (b) profile last-seen date recorded (all within Jan–Aug 2026, {recent} of {n} within the last 60 days); (c) company website live and describing mould manufacture; (d) email addresses are syntactically valid and taken from the company's own pages; (e) phone numbers are the company's published lines. Not performed: dialling numbers or sending test emails."),
 ("Coverage of the quality bar", f"Named contact: {n}/{n}. LinkedIn available: {n}/{n}. Company phone: {phones}/{n}. Company email: {emails}/{n}. Source URL: {n}/{n}. Commercial mould makers (sell moulds to others): {commercial}; the rest are moulders whose in-house tool room builds moulds (marked 'Captive' or 'Moulder with in-house tool room'). One row (Sri Lakshmi Engineering) is low confidence and marked."),
 ("Excluded on purpose", "Raw-material and mould-base suppliers (e.g. DME/Milacron Belgaum), distributors, foreign-headquartered estimating offices in India (Cavalier Tool Chennai, MDL Coimbatore), pure moulders with no mould-making, and companies where no costing/quotation person could be named. Helvoet India (Dutch parent, moulder) was dropped for the same reason; VEM Tooling was kept because its Pune plant builds the moulds."),
 ("Assumptions and limits", "Apollo and other paid databases were not used, so direct dials and personal work emails are absent. Profiles reflect what the individuals wrote; titles are quoted as published. 'Profile last seen' is the date the public profile was last indexed, not a guarantee of current employment. Second contacts are listed in Notes where found."),
 ("Suggested next step", "Apollo can enrich these 30 by company domain + name to obtain verified work emails and direct dials; the Notes column gives a second name at 3 companies for redundancy."),
]
ws2 = wb.create_sheet("Methodology"); ws2.append(["Item", "Description"])
for c in ws2[1]:
    c.font = bold; c.fill = fill
for k, v in M:
    ws2.append([k, v])
ws2.column_dimensions["A"].width = 34; ws2.column_dimensions["B"].width = 120
for row in ws2.iter_rows(min_row=2):
    for c in row:
        c.alignment = Alignment(wrap_text=True, vertical="top")
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "India_Plastic_Mould_Makers_Estimation_Leads.xlsx")
wb.save(out); print(out, n, "rows")
